table 'Parameters'
	lineageTag: 929d60ff-7b72-40c0-b051-d2638d6e0159

	measure 'Base Salary' = 50000
		lineageTag: f4da14df-598b-41c5-b271-30f322bbcca5

	measure 'Commission Rate' = 18.399999999999999
		lineageTag: 66b138bd-2d6c-4a09-97e6-e3233823a203

	measure 'New Quota' = 500000
		lineageTag: fde2501b-fc20-4ad4-8570-e3a2d6ada2de

	measure 'Sort by' = "Names"
		lineageTag: 36781557-6cf9-46c3-9639-a49fc42ef0cb

	measure 'New Business Growth' = 0.59999999999999998
		lineageTag: a535c1d2-c5c6-4a43-8070-957aa571a989

	measure 'Churn Rate' = 0.064000000000000001
		lineageTag: c7acc021-03f2-4144-856c-87d1665cb977

	partition 'Parameters' = m
		mode: import
		source =
			let
				Source = #table(type table [], {})
			in
				Source
