table 'Sales Target'
	lineageTag: 57e23a7e-7233-4d34-a4b4-cc123b0a1382

	column 'Category'
		dataType: string
		lineageTag: 338a5486-42ec-44a1-bf03-8baa9a4388f3
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		lineageTag: 4f80f7e1-443d-4e6b-a0ac-0d9b2e383be4
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

	column 'Segment'
		dataType: string
		lineageTag: e67da5ed-42c2-4630-a13b-fa360478025a
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		lineageTag: 7d281042-531f-4dc2-aa9b-2e272ef3ea1b
		summarizeBy: sum
		sourceColumn: Sales Target

		annotation SummarizationSetBy = Automatic

	partition 'Sales Target' = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("Data/Superstore/Sales Target.xlsx"), null, true),
				Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				PromotedHeaders = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])
				, ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"Category", type text}, {"Order Date", type date}, {"Segment", type text}, {"Sales Target", Int64.Type}})
			in
				ChangedTypes
