table 'Sales Commission'
	lineageTag: 0c729492-b325-4c0e-8ce6-8c4482b52fe8

	column 'Order Date'
		dataType: dateTime
		lineageTag: 92a45ed7-fd68-4e8f-896b-e34f908e1a82
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

	column 'Region'
		dataType: string
		lineageTag: 93dcb8e3-ec97-43a5-89b6-4f1c481e57ea
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Sales Person'
		dataType: string
		lineageTag: 9b9fd1b8-9a02-4b68-86a5-f789fb913e54
		summarizeBy: none
		sourceColumn: Sales Person

		annotation SummarizationSetBy = Automatic

	column 'Sales'
		dataType: int64
		lineageTag: d79b1a93-d92b-4eb5-b730-09cdba282dcb
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	measure 'Achievement (estimated)' = 'Sales Commission'[Sales]
		lineageTag: db736ee4-8989-49eb-82a0-fa1097c06f52

	measure 'Achieved Quota' = IF(SUM('Sales Commission'[Achievement (copy)]) >= 'Parameters'[New Quota] , "100% +" , IF( SUM('Sales Commission'[Achievement (copy)]) >= 0.75 * 'Parameters'[New Quota] , "75-100%" , IF( SUM('Sales Commission'[Achievement (copy)]) >= 0.5 * 'Parameters'[New Quota] , "50-75%" , "Below 50%" ))
		lineageTag: 427090d9-bd87-4e37-9c70-ef01eb641e43

	measure 'Base (Variable)' = 'Parameters'[Base Salary]
		lineageTag: 9bfa3319-dec7-4a2e-a77e-28444bb30497

	measure '% of quota achieved' = AVERAGE('Sales Commission'[Achievement (copy)])/'Parameters'[New Quota]
		lineageTag: 53d858fd-c609-41d0-a1f6-640a4015df0a

	measure 'Rank over 3' = ROUND(RANKX() / 3 - 0.6,0) + 1
		lineageTag: 7ba1996b-ea08-4855-9515-20dce9715b87

	measure 'Sort by field' = IF('Parameters'[Parameter 1 1]="Names" , 0 , IF( 'Parameters'[Parameter 1 1]="% quota descending" , -'Sales Commission'[Calculation_0440925131659539] , 'Sales Commission'[Calculation_0440925131659539] )
		lineageTag: 10e84f03-56b1-4a95-bcc9-685a1606c7e5

	measure 'Commission (Variable)' = ('Parameters'[Commission Rate]*'Sales Commission'[Sales])/100
		lineageTag: a1f6000e-7976-4512-a577-b41ba8d73f6f

	measure 'Estimate Compensation label' = "Estimated Compensation:"
		lineageTag: 7a97f4c6-c426-42b4-b9f2-f3b64fc33098

	measure 'OTE (Variable)' = 'Parameters'[Base Salary] + ('Parameters'[Commission Rate]*'Parameters'[New Quota])/100
		lineageTag: 7784fb9f-b3bf-4238-af7b-5691b417536d

	measure 'Total Compensation' = MIN('Sales Commission'[Base (Variable)]) + SUM('Sales Commission'[Commission (Variable)])
		lineageTag: c7914a43-9e28-4397-99b7-63d4413f4080

	measure 'Total Sales label' = "Total Sales:"
		lineageTag: 3b28f6e4-26aa-4443-bbd7-9cf518f1e6b2

	measure 'Base Salary' = 50000
		lineageTag: feb9dc8d-880f-4016-9536-a9898dc1116f

	measure 'Commission Rate' = 18.399999999999999
		lineageTag: 58158dc4-ca40-48d6-b10b-d29dd0f0e582

	measure 'New Quota' = 500000
		lineageTag: 5b646afd-1160-403b-8307-ced6ed77e8b4

	measure 'Sort by' = "Names"
		lineageTag: 3bc0778b-5ece-4337-afab-f4e03574ccfc

	partition 'Sales Commission' = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("Data/Superstore/Sales Commission.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				, ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"Order Date", type datetime}, {"Region", type text}, {"Sales Person", type text}, {"Sales", Int64.Type}})
			in
				ChangedTypes
