table 'Sample - Superstore'
	lineageTag: 8456ed92-d581-4b98-b854-4cab27359ccf

	column 'Row ID'
		dataType: int64
		lineageTag: c92cfad1-2d76-43ac-ad2b-3e490c3a7458
		summarizeBy: sum
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 5b5e34cf-bea9-40a1-be32-6900adefdde6
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		lineageTag: 498987d7-7305-48e1-8e3e-9d709c643118
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		lineageTag: 53466446-eefe-4a38-8dc2-087fde867afe
		summarizeBy: none
		sourceColumn: Ship Date

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: c77873c8-c3a4-44ea-96ff-b29e38481eca
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: f2985092-10ef-4868-8daa-75624ddf2556
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 51f4f6b6-b8aa-404a-adcc-6eab7788ac17
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Segment'
		dataType: string
		lineageTag: 60158126-d0b0-46f6-9726-691d8fde9e1b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: 0ed1984d-fda6-4423-b741-aee38247c2d8
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column 'City'
		dataType: string
		lineageTag: 3c8fa0f7-4039-4a1e-88ba-b80b7a164525
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'State/Province'
		dataType: string
		lineageTag: 7db2198b-6d70-4dcc-bd1b-4d3f38f292cd
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 32937acb-48ea-4d70-8460-6c9910502329
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column 'Region'
		dataType: string
		lineageTag: 84e990b6-b46b-4b70-aee2-9a5092b4d9a4
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 83c0a499-b3e8-40cd-9d9c-27902a9ac257
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Category'
		dataType: string
		lineageTag: 0c536c65-c9ae-449e-84ef-4138c813e6fd
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 5f1b5754-e3ab-4932-9f2e-c70c2f881f85
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 9c373341-b63c-4771-b3da-77f80c9e35a3
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Sales'
		dataType: double
		lineageTag: 4104e7d8-350e-4f67-813d-ca2e991a9982
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column 'Quantity'
		dataType: int64
		lineageTag: 79fc06e5-27e8-4fb8-987e-acde69f54c18
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Discount'
		dataType: double
		lineageTag: a7aaf6c0-ae50-47eb-8756-72a5c0d1865a
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column 'Profit'
		dataType: double
		lineageTag: 6915f249-e3e1-4a9f-b444-ff54551a438a
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Regional Manager'
		dataType: string
		lineageTag: 7592b06c-c5b1-4e42-a842-94cf4317eec2
		summarizeBy: none
		sourceColumn: Regional Manager

		annotation SummarizationSetBy = Automatic

	column 'Returned'
		dataType: string
		lineageTag: fe84065c-b8cb-4b64-87ce-e6876ee526a4
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID (Returns)'
		dataType: string
		lineageTag: 274f902f-6be2-4c66-a34c-3b437e5440e9
		summarizeBy: none
		sourceColumn: Order ID (Returns)

		annotation SummarizationSetBy = Automatic

	column 'Region (People)'
		dataType: string
		lineageTag: 7d62ae74-7077-46e2-851c-19d50efefe70
		summarizeBy: none
		sourceColumn: Region (People)

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		lineageTag: 85c2c611-6d57-496b-8f47-f89843a59a0a
		summarizeBy: sum
		sourceColumn: Sales Target

		annotation SummarizationSetBy = Automatic

	measure 'Days to Ship Actual' = DATEDIFF('Sample - Superstore'[Order Date], 'Sample - Superstore'[Ship Date], DAY)
		lineageTag: e4e4b28f-ce73-4f5d-9f38-59e2631f4fd1

	measure 'Sales Forecast' = 'Sample - Superstore'[Sales]*(1-'Parameters'[Parameter 2])*(1+'Parameters'[Parameter 1])
		lineageTag: b9f626a8-0454-4b6b-97b3-bf2cd0f56d8c

	measure 'Ship Status' = IF('Sample - Superstore'[Calculation_0831103151444568]> 'Sample - Superstore'[Calculation_6861103170623145] , "Shipped Late" , IF( 'Sample - Superstore'[Calculation_0831103151444568]= 'Sample - Superstore'[Calculation_6861103170623145] , "Shipped On Time" , "Shipped Early" )
		lineageTag: bb79f8b2-2722-4f72-bbf2-39ae2a8282be

	measure 'Days to Ship Scheduled' = CASE 'Sample - Superstore'[Ship Mode] WHEN "Same Day" , 0 WHEN "First Class" , 1 WHEN "Second Class" , 3 WHEN "Standard Class" , 6
		lineageTag: c1773a9a-1e49-4497-b011-168391cec3f8

	measure 'Order Profitable?' = CALCULATE(SUM('Sample - Superstore'[Profit]), ALLEXCEPT(Sample - Superstore, 'Sample - Superstore'[Order ID])>0 // calculates the profit at the order level
		lineageTag: b4ff9b6f-d6f5-47ef-a07c-01e56af22629

	measure 'Sales per Customer' = SUM('Sample - Superstore'[Sales])/DISTINCTCOUNT('Sample - Superstore'[Customer Name])
		lineageTag: 6cd624d8-877e-4406-aeec-3d9cc0039096

	measure 'Profit Ratio' = SUM('Sample - Superstore'[Profit])/SUM('Sample - Superstore'[Sales])
		lineageTag: cd3ba810-7b7a-4ca8-93ad-43d44163e227

	measure 'Sales above Target?' = IF(SUM('Sample - Superstore'[Sales])>SUM('Sample - Superstore'[Sales Target]) , "Above Target" , "Below Target" )
		lineageTag: 26073974-d97e-4ba0-846f-e261d3941207

	measure 'Units estimate' = ROUND('Sample - Superstore'[Quantity]*(1-'Parameters'[Parameter 2])*(1+'Parameters'[Parameter 1]),0)
		lineageTag: 3856de0c-e7bc-441c-a32a-72fb061e77f0

	measure 'Profit per Order' = SUM('Sample - Superstore'[Profit])/DISTINCTCOUNT('Sample - Superstore'[Order ID])
		lineageTag: 55a61a7d-5391-4e14-beef-aa489c7a2bca

	measure 'New Business Growth' = 0.59999999999999998
		lineageTag: ff7427da-a059-4c97-8f93-e9c7cf4190c9

	measure 'Churn Rate' = 0.064000000000000001
		lineageTag: 493eb5be-5ca2-4b26-8192-b0c9eaae5fa2

	partition 'Sample - Superstore' = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("Data/Superstore/Sample - Superstore.xls"), null, true),
				Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				PromotedHeaders = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true])
				, ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}, {"Regional Manager", type text}, {"Returned", type text}, {"Order ID (Returns)", type text}, {"Region (People)", type text}, {"Sales Target", Int64.Type}})
			in
				ChangedTypes
